/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BeamioIndexerDiamond } from './BeamioIndexerDiamond.js';
export type { BeamioIndexerDiamond3 } from './BeamioIndexerDiamond3.js';