/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { Nonces4, Nonces4Interface } from "../../../../contracts/utils/Nonces.sol/Nonces4.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "currentNonce",
        "type": "uint256"
      }
    ],
    "name": "InvalidAccountNonce",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "nonces",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class Nonces4__factory {
    static readonly abi = _abi;
    static createInterface(): Nonces4Interface {
      return new Interface(_abi) as Nonces4Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): Nonces4 {
      return new Contract(address, _abi, runner) as unknown as Nonces4;
    }
  }
  