/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OwnershipFacet } from './OwnershipFacet.js';
export type { OwnershipFacet3 } from './OwnershipFacet3.js';