/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as beamioErc1155LogicSol from './BeamioERC1155Logic.sol/index.js';
export type { beamioErc1155LogicSol };
import type * as beamioUserCardSol from './BeamioUserCard.sol/index.js';
export type { beamioUserCardSol };