/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accountRegistrySol from './AccountRegistry.sol/index.js';
export type { accountRegistrySol };
import type * as guardianNodesInfoV6Sol from './GuardianNodesInfoV6.sol/index.js';
export type { guardianNodesInfoV6Sol };
export type { AddressPGP } from './AddressPGP.js';