/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MerchantPOSManagementInterface extends Interface {
    getFunction(nameOrSignature: "getMerchantPOSCount" | "getMerchantPOSList" | "getPOSMerchant" | "isPOSRegistered" | "registerPOS" | "removePOS"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "POSRegistered" | "POSRemoved"): EventFragment;

    encodeFunctionData(functionFragment: 'getMerchantPOSCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMerchantPOSList', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPOSMerchant', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isPOSRegistered', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'registerPOS', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removePOS', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getMerchantPOSCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMerchantPOSList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPOSMerchant', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPOSRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerPOS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removePOS', data: BytesLike): Result;
  }

  
    export namespace POSRegisteredEvent {
      export type InputTuple = [merchant: AddressLike, pos: AddressLike];
      export type OutputTuple = [merchant: string, pos: string];
      export interface OutputObject {merchant: string, pos: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace POSRemovedEvent {
      export type InputTuple = [merchant: AddressLike, pos: AddressLike];
      export type OutputTuple = [merchant: string, pos: string];
      export interface OutputObject {merchant: string, pos: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MerchantPOSManagement extends BaseContract {
    
    connect(runner?: ContractRunner | null): MerchantPOSManagement;
    waitForDeployment(): Promise<this>;

    interface: MerchantPOSManagementInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getMerchantPOSCount: TypedContractMethod<
      [merchant: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getMerchantPOSList: TypedContractMethod<
      [merchant: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getPOSMerchant: TypedContractMethod<
      [pos: AddressLike, ],
      [string],
      'view'
    >
    

    
    isPOSRegistered: TypedContractMethod<
      [merchant: AddressLike, pos: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    registerPOS: TypedContractMethod<
      [pos: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removePOS: TypedContractMethod<
      [pos: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getMerchantPOSCount'): TypedContractMethod<
      [merchant: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMerchantPOSList'): TypedContractMethod<
      [merchant: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPOSMerchant'): TypedContractMethod<
      [pos: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isPOSRegistered'): TypedContractMethod<
      [merchant: AddressLike, pos: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerPOS'): TypedContractMethod<
      [pos: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removePOS'): TypedContractMethod<
      [pos: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'POSRegistered'): TypedContractEvent<POSRegisteredEvent.InputTuple, POSRegisteredEvent.OutputTuple, POSRegisteredEvent.OutputObject>;
getEvent(key: 'POSRemoved'): TypedContractEvent<POSRemovedEvent.InputTuple, POSRemovedEvent.OutputTuple, POSRemovedEvent.OutputObject>;

    filters: {
      
      'POSRegistered(address,address)': TypedContractEvent<POSRegisteredEvent.InputTuple, POSRegisteredEvent.OutputTuple, POSRegisteredEvent.OutputObject>;
      POSRegistered: TypedContractEvent<POSRegisteredEvent.InputTuple, POSRegisteredEvent.OutputTuple, POSRegisteredEvent.OutputObject>;
    

      'POSRemoved(address,address)': TypedContractEvent<POSRemovedEvent.InputTuple, POSRemovedEvent.OutputTuple, POSRemovedEvent.OutputObject>;
      POSRemoved: TypedContractEvent<POSRemovedEvent.InputTuple, POSRemovedEvent.OutputTuple, POSRemovedEvent.OutputObject>;
    
    };
  }