/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CatalogFacet__factory } from './CatalogFacet__factory.js';
export { CatalogFacet3__factory } from './CatalogFacet3__factory.js';