/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDiamondCut__factory } from './IDiamondCut__factory.js';
export { IDiamondCut2__factory } from './IDiamondCut2__factory.js';