/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC1155__factory } from './IERC1155__factory.js';
export { IERC11552__factory } from './IERC11552__factory.js';