/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { HexUtils, HexUtilsInterface } from "../../b-unit/HexUtils.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "value",
        "type": "bytes32"
      }
    ],
    "name": "toHexString",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080806040523460195761021d908161001e823930815050f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c63edb961ff14610024575f80fd5b602036600319011261019957600435604061003e8161019d565b91601083526f181899199a1a9b1b9c1cb0b131b232b360811b6020840152610066608061019d565b6042815260208101939091906060368637825115610185576030855382516001101561018557607860218401535f5b602081106100cb575050508151928391602083525180918160208501528484015e5f828201840152601f01601f19168101030190f35b8060031b908015918181046008148317156101715760f80360f881116101715784901c6001600160f81b0319610108600483901c600f16866101d6565b51168260011b9383850460021417156101715783600201908160021161017157610135905f1a91886101d6565b536001600160f81b03199061014d90600f16856101d6565b511691600301806003116101715761016a6001935f1a91876101d6565b5301610095565b634e487b7160e01b5f52601160045260245ffd5b634e487b7160e01b5f52603260045260245ffd5b5f80fd5b6040519190601f01601f191682016001600160401b038111838210176101c257604052565b634e487b7160e01b5f52604160045260245ffd5b90815181101561018557016020019056fea26469706673582212204ee151384505e8fa8c4f8b5275c682c3ceb321dc931584c760284748561dca3164736f6c63430008210033";

  
      type HexUtilsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: HexUtilsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class HexUtils__factory extends ContractFactory {
    
      constructor(...args: HexUtilsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<HexUtils & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): HexUtils__factory {
      return super.connect(runner) as HexUtils__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): HexUtilsInterface {
      return new Interface(_abi) as HexUtilsInterface;
    }
    
    override attach(address: string | Addressable): HexUtils {
      return super.attach(address) as HexUtils;
    }
  static connect(address: string, runner?: ContractRunner | null): HexUtils {
      return new Contract(address, _abi, runner) as unknown as HexUtils;
    }
  }

  
  