/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AddressPGP__factory } from './AddressPGP__factory.js';
export { AddressPGP2__factory } from './AddressPGP2__factory.js';