/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155Receiver } from './IERC1155Receiver.js';
export type { IERC1155Receiver2 } from './IERC1155Receiver2.js';