/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC5267__factory } from './IERC5267__factory.js';
export { IERC52672__factory } from './IERC52672__factory.js';