/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IBeamioAccountFactoryV07, IBeamioAccountFactoryV07Interface } from "../../../../src 2/BeamioUserCard/BeamioERC1155Logic.sol/IBeamioAccountFactoryV07.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "creator",
        "type": "address"
      }
    ],
    "name": "beamioAccountOf",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "a",
        "type": "address"
      }
    ],
    "name": "isBeamioAccount",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IBeamioAccountFactoryV07__factory {
    static readonly abi = _abi;
    static createInterface(): IBeamioAccountFactoryV07Interface {
      return new Interface(_abi) as IBeamioAccountFactoryV07Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IBeamioAccountFactoryV07 {
      return new Contract(address, _abi, runner) as unknown as IBeamioAccountFactoryV07;
    }
  }
  