/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IBeamioDeployerV074, IBeamioDeployerV074Interface } from "../../../BeamioUserCard/BeamioUserCardFactoryPaymasterV07.sol/IBeamioDeployerV074.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "initCode",
        "type": "bytes"
      }
    ],
    "name": "deploy",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IBeamioDeployerV074__factory {
    static readonly abi = _abi;
    static createInterface(): IBeamioDeployerV074Interface {
      return new Interface(_abi) as IBeamioDeployerV074Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IBeamioDeployerV074 {
      return new Contract(address, _abi, runner) as unknown as IBeamioDeployerV074;
    }
  }
  