/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Base64__factory } from './Base64__factory.js';
export { Base642__factory } from './Base642__factory.js';