/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc721MetadataSol from './IERC721Metadata.sol/index.js';
export type { ierc721MetadataSol };