/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BeamioOracle } from './BeamioOracle.js';
export type { BeamioOracle2 } from './BeamioOracle2.js';