/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StatsFacet__factory } from './StatsFacet__factory.js';
export { StatsFacet4__factory } from './StatsFacet4__factory.js';