/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BeamioIndexerDiamond__factory } from './BeamioIndexerDiamond__factory.js';
export { BeamioIndexerDiamond3__factory } from './BeamioIndexerDiamond3__factory.js';