/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155Supply__factory } from './ERC1155Supply__factory.js';
export { ERC1155Supply2__factory } from './ERC1155Supply2__factory.js';