/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TaskFacet__factory } from './TaskFacet__factory.js';
export { TaskFacet2__factory } from './TaskFacet2__factory.js';