/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GuardianNodesInfoV6 } from './GuardianNodesInfoV6.js';
export type { GuardianNodesInfoV62 } from './GuardianNodesInfoV62.js';