/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiamondCutFacet__factory } from './DiamondCutFacet__factory.js';
export { DiamondCutFacet2__factory } from './DiamondCutFacet2__factory.js';