/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155Burnable__factory } from './ERC1155Burnable__factory.js';
export { ERC1155Burnable2__factory } from './ERC1155Burnable2__factory.js';