/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface BeamioUserCardFactoryPaymasterV07Interface extends Interface {
    getFunction(nameOrSignature: "USDC" | "USDC_TOKEN" | "_aaFactory" | "aaFactory" | "beamioUserCardOwner" | "cardsOfOwner" | "changePaymasterStatus" | "createCardCollectionWithInitCode" | "defaultRedeemModule" | "deployer" | "isBeamioUserCard" | "isCardOfOwner" | "isPaymaster" | "isTokenIdIssued" | "issueTokenId" | "latestCardOfOwner" | "nextFungibleId" | "nextNftId" | "owner" | "quoteCurrencyAmountInUSDC6" | "quoteHelper" | "quoteUnitPointInUSDC6" | "redeemForUser" | "redeemPoolForUser" | "registerExistingCard" | "setAAFactory" | "setDeployer" | "setQuoteHelper" | "setRedeemModule" | "tokenIdIssued" | "transferOwner"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AAFactoryChanged" | "CardDeployed" | "CardRegistered" | "DefaultRedeemModuleUpdated" | "DeployerChanged" | "OwnerChanged" | "PaymasterStatusChanged" | "QuoteHelperChanged" | "RedeemExecuted" | "TokenIdIssued"): EventFragment;

    encodeFunctionData(functionFragment: 'USDC', values?: undefined): string;
encodeFunctionData(functionFragment: 'USDC_TOKEN', values?: undefined): string;
encodeFunctionData(functionFragment: '_aaFactory', values?: undefined): string;
encodeFunctionData(functionFragment: 'aaFactory', values?: undefined): string;
encodeFunctionData(functionFragment: 'beamioUserCardOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cardsOfOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'changePaymasterStatus', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'createCardCollectionWithInitCode', values: [AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'defaultRedeemModule', values?: undefined): string;
encodeFunctionData(functionFragment: 'deployer', values?: undefined): string;
encodeFunctionData(functionFragment: 'isBeamioUserCard', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isCardOfOwner', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isPaymaster', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isTokenIdIssued', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'issueTokenId', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'latestCardOfOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nextFungibleId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextNftId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'quoteCurrencyAmountInUSDC6', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteHelper', values?: undefined): string;
encodeFunctionData(functionFragment: 'quoteUnitPointInUSDC6', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'redeemForUser', values: [AddressLike, string, AddressLike]): string;
encodeFunctionData(functionFragment: 'redeemPoolForUser', values: [AddressLike, string, AddressLike]): string;
encodeFunctionData(functionFragment: 'registerExistingCard', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setAAFactory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setDeployer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setQuoteHelper', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setRedeemModule', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tokenIdIssued', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwner', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'USDC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'USDC_TOKEN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: '_aaFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'aaFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'beamioUserCardOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cardsOfOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'changePaymasterStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCardCollectionWithInitCode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'defaultRedeemModule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isBeamioUserCard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCardOfOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPaymaster', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTokenIdIssued', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueTokenId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestCardOfOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextFungibleId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextNftId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteCurrencyAmountInUSDC6', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteHelper', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteUnitPointInUSDC6', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeemForUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeemPoolForUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerExistingCard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAAFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDeployer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setQuoteHelper', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRedeemModule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenIdIssued', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwner', data: BytesLike): Result;
  }

  
    export namespace AAFactoryChangedEvent {
      export type InputTuple = [oldFactory: AddressLike, newFactory: AddressLike];
      export type OutputTuple = [oldFactory: string, newFactory: string];
      export interface OutputObject {oldFactory: string, newFactory: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CardDeployedEvent {
      export type InputTuple = [cardOwner: AddressLike, card: AddressLike, currency: BigNumberish, priceE18: BigNumberish];
      export type OutputTuple = [cardOwner: string, card: string, currency: bigint, priceE18: bigint];
      export interface OutputObject {cardOwner: string, card: string, currency: bigint, priceE18: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CardRegisteredEvent {
      export type InputTuple = [cardOwner: AddressLike, card: AddressLike];
      export type OutputTuple = [cardOwner: string, card: string];
      export interface OutputObject {cardOwner: string, card: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DefaultRedeemModuleUpdatedEvent {
      export type InputTuple = [oldM: AddressLike, newM: AddressLike];
      export type OutputTuple = [oldM: string, newM: string];
      export interface OutputObject {oldM: string, newM: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DeployerChangedEvent {
      export type InputTuple = [oldD: AddressLike, newD: AddressLike];
      export type OutputTuple = [oldD: string, newD: string];
      export interface OutputObject {oldD: string, newD: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerChangedEvent {
      export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [oldOwner: string, newOwner: string];
      export interface OutputObject {oldOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymasterStatusChangedEvent {
      export type InputTuple = [account: AddressLike, allowed: boolean];
      export type OutputTuple = [account: string, allowed: boolean];
      export interface OutputObject {account: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QuoteHelperChangedEvent {
      export type InputTuple = [oldH: AddressLike, newH: AddressLike];
      export type OutputTuple = [oldH: string, newH: string];
      export interface OutputObject {oldH: string, newH: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedeemExecutedEvent {
      export type InputTuple = [card: AddressLike, user: AddressLike, redeemHash: BytesLike];
      export type OutputTuple = [card: string, user: string, redeemHash: string];
      export interface OutputObject {card: string, user: string, redeemHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenIdIssuedEvent {
      export type InputTuple = [card: AddressLike, id: BigNumberish, isNft: boolean];
      export type OutputTuple = [card: string, id: bigint, isNft: boolean];
      export interface OutputObject {card: string, id: bigint, isNft: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BeamioUserCardFactoryPaymasterV07 extends BaseContract {
    
    connect(runner?: ContractRunner | null): BeamioUserCardFactoryPaymasterV07;
    waitForDeployment(): Promise<this>;

    interface: BeamioUserCardFactoryPaymasterV07Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    USDC: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    USDC_TOKEN: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    _aaFactory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    aaFactory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    beamioUserCardOwner: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    cardsOfOwner: TypedContractMethod<
      [cardOwner: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    changePaymasterStatus: TypedContractMethod<
      [a: AddressLike, ok: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    createCardCollectionWithInitCode: TypedContractMethod<
      [cardOwner: AddressLike, currency: BigNumberish, priceInCurrencyE18: BigNumberish, initCode: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    defaultRedeemModule: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    deployer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isBeamioUserCard: TypedContractMethod<
      [card: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isCardOfOwner: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isPaymaster: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isTokenIdIssued: TypedContractMethod<
      [card: AddressLike, id: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    issueTokenId: TypedContractMethod<
      [card: AddressLike, isNft: boolean, ],
      [bigint],
      'nonpayable'
    >
    

    
    latestCardOfOwner: TypedContractMethod<
      [cardOwner: AddressLike, ],
      [string],
      'view'
    >
    

    
    nextFungibleId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextNftId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    quoteCurrencyAmountInUSDC6: TypedContractMethod<
      [cur: BigNumberish, amount6: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    quoteHelper: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    quoteUnitPointInUSDC6: TypedContractMethod<
      [card: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    redeemForUser: TypedContractMethod<
      [cardAddr: AddressLike, code: string, userEOA: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    redeemPoolForUser: TypedContractMethod<
      [cardAddr: AddressLike, code: string, userEOA: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registerExistingCard: TypedContractMethod<
      [cardOwner: AddressLike, card: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setAAFactory: TypedContractMethod<
      [f: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDeployer: TypedContractMethod<
      [d: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setQuoteHelper: TypedContractMethod<
      [h: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRedeemModule: TypedContractMethod<
      [m: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    tokenIdIssued: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    transferOwner: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'USDC'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'USDC_TOKEN'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: '_aaFactory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'aaFactory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'beamioUserCardOwner'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cardsOfOwner'): TypedContractMethod<
      [cardOwner: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'changePaymasterStatus'): TypedContractMethod<
      [a: AddressLike, ok: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createCardCollectionWithInitCode'): TypedContractMethod<
      [cardOwner: AddressLike, currency: BigNumberish, priceInCurrencyE18: BigNumberish, initCode: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'defaultRedeemModule'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deployer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isBeamioUserCard'): TypedContractMethod<
      [card: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isCardOfOwner'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isPaymaster'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isTokenIdIssued'): TypedContractMethod<
      [card: AddressLike, id: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'issueTokenId'): TypedContractMethod<
      [card: AddressLike, isNft: boolean, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'latestCardOfOwner'): TypedContractMethod<
      [cardOwner: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nextFungibleId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextNftId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'quoteCurrencyAmountInUSDC6'): TypedContractMethod<
      [cur: BigNumberish, amount6: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quoteHelper'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'quoteUnitPointInUSDC6'): TypedContractMethod<
      [card: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redeemForUser'): TypedContractMethod<
      [cardAddr: AddressLike, code: string, userEOA: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'redeemPoolForUser'): TypedContractMethod<
      [cardAddr: AddressLike, code: string, userEOA: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerExistingCard'): TypedContractMethod<
      [cardOwner: AddressLike, card: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAAFactory'): TypedContractMethod<
      [f: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDeployer'): TypedContractMethod<
      [d: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setQuoteHelper'): TypedContractMethod<
      [h: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRedeemModule'): TypedContractMethod<
      [m: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tokenIdIssued'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwner'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AAFactoryChanged'): TypedContractEvent<AAFactoryChangedEvent.InputTuple, AAFactoryChangedEvent.OutputTuple, AAFactoryChangedEvent.OutputObject>;
getEvent(key: 'CardDeployed'): TypedContractEvent<CardDeployedEvent.InputTuple, CardDeployedEvent.OutputTuple, CardDeployedEvent.OutputObject>;
getEvent(key: 'CardRegistered'): TypedContractEvent<CardRegisteredEvent.InputTuple, CardRegisteredEvent.OutputTuple, CardRegisteredEvent.OutputObject>;
getEvent(key: 'DefaultRedeemModuleUpdated'): TypedContractEvent<DefaultRedeemModuleUpdatedEvent.InputTuple, DefaultRedeemModuleUpdatedEvent.OutputTuple, DefaultRedeemModuleUpdatedEvent.OutputObject>;
getEvent(key: 'DeployerChanged'): TypedContractEvent<DeployerChangedEvent.InputTuple, DeployerChangedEvent.OutputTuple, DeployerChangedEvent.OutputObject>;
getEvent(key: 'OwnerChanged'): TypedContractEvent<OwnerChangedEvent.InputTuple, OwnerChangedEvent.OutputTuple, OwnerChangedEvent.OutputObject>;
getEvent(key: 'PaymasterStatusChanged'): TypedContractEvent<PaymasterStatusChangedEvent.InputTuple, PaymasterStatusChangedEvent.OutputTuple, PaymasterStatusChangedEvent.OutputObject>;
getEvent(key: 'QuoteHelperChanged'): TypedContractEvent<QuoteHelperChangedEvent.InputTuple, QuoteHelperChangedEvent.OutputTuple, QuoteHelperChangedEvent.OutputObject>;
getEvent(key: 'RedeemExecuted'): TypedContractEvent<RedeemExecutedEvent.InputTuple, RedeemExecutedEvent.OutputTuple, RedeemExecutedEvent.OutputObject>;
getEvent(key: 'TokenIdIssued'): TypedContractEvent<TokenIdIssuedEvent.InputTuple, TokenIdIssuedEvent.OutputTuple, TokenIdIssuedEvent.OutputObject>;

    filters: {
      
      'AAFactoryChanged(address,address)': TypedContractEvent<AAFactoryChangedEvent.InputTuple, AAFactoryChangedEvent.OutputTuple, AAFactoryChangedEvent.OutputObject>;
      AAFactoryChanged: TypedContractEvent<AAFactoryChangedEvent.InputTuple, AAFactoryChangedEvent.OutputTuple, AAFactoryChangedEvent.OutputObject>;
    

      'CardDeployed(address,address,uint8,uint256)': TypedContractEvent<CardDeployedEvent.InputTuple, CardDeployedEvent.OutputTuple, CardDeployedEvent.OutputObject>;
      CardDeployed: TypedContractEvent<CardDeployedEvent.InputTuple, CardDeployedEvent.OutputTuple, CardDeployedEvent.OutputObject>;
    

      'CardRegistered(address,address)': TypedContractEvent<CardRegisteredEvent.InputTuple, CardRegisteredEvent.OutputTuple, CardRegisteredEvent.OutputObject>;
      CardRegistered: TypedContractEvent<CardRegisteredEvent.InputTuple, CardRegisteredEvent.OutputTuple, CardRegisteredEvent.OutputObject>;
    

      'DefaultRedeemModuleUpdated(address,address)': TypedContractEvent<DefaultRedeemModuleUpdatedEvent.InputTuple, DefaultRedeemModuleUpdatedEvent.OutputTuple, DefaultRedeemModuleUpdatedEvent.OutputObject>;
      DefaultRedeemModuleUpdated: TypedContractEvent<DefaultRedeemModuleUpdatedEvent.InputTuple, DefaultRedeemModuleUpdatedEvent.OutputTuple, DefaultRedeemModuleUpdatedEvent.OutputObject>;
    

      'DeployerChanged(address,address)': TypedContractEvent<DeployerChangedEvent.InputTuple, DeployerChangedEvent.OutputTuple, DeployerChangedEvent.OutputObject>;
      DeployerChanged: TypedContractEvent<DeployerChangedEvent.InputTuple, DeployerChangedEvent.OutputTuple, DeployerChangedEvent.OutputObject>;
    

      'OwnerChanged(address,address)': TypedContractEvent<OwnerChangedEvent.InputTuple, OwnerChangedEvent.OutputTuple, OwnerChangedEvent.OutputObject>;
      OwnerChanged: TypedContractEvent<OwnerChangedEvent.InputTuple, OwnerChangedEvent.OutputTuple, OwnerChangedEvent.OutputObject>;
    

      'PaymasterStatusChanged(address,bool)': TypedContractEvent<PaymasterStatusChangedEvent.InputTuple, PaymasterStatusChangedEvent.OutputTuple, PaymasterStatusChangedEvent.OutputObject>;
      PaymasterStatusChanged: TypedContractEvent<PaymasterStatusChangedEvent.InputTuple, PaymasterStatusChangedEvent.OutputTuple, PaymasterStatusChangedEvent.OutputObject>;
    

      'QuoteHelperChanged(address,address)': TypedContractEvent<QuoteHelperChangedEvent.InputTuple, QuoteHelperChangedEvent.OutputTuple, QuoteHelperChangedEvent.OutputObject>;
      QuoteHelperChanged: TypedContractEvent<QuoteHelperChangedEvent.InputTuple, QuoteHelperChangedEvent.OutputTuple, QuoteHelperChangedEvent.OutputObject>;
    

      'RedeemExecuted(address,address,bytes32)': TypedContractEvent<RedeemExecutedEvent.InputTuple, RedeemExecutedEvent.OutputTuple, RedeemExecutedEvent.OutputObject>;
      RedeemExecuted: TypedContractEvent<RedeemExecutedEvent.InputTuple, RedeemExecutedEvent.OutputTuple, RedeemExecutedEvent.OutputObject>;
    

      'TokenIdIssued(address,uint256,bool)': TypedContractEvent<TokenIdIssuedEvent.InputTuple, TokenIdIssuedEvent.OutputTuple, TokenIdIssuedEvent.OutputObject>;
      TokenIdIssued: TypedContractEvent<TokenIdIssuedEvent.InputTuple, TokenIdIssuedEvent.OutputTuple, TokenIdIssuedEvent.OutputObject>;
    
    };
  }