/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiamondCutFacet } from './DiamondCutFacet.js';
export type { DiamondCutFacet2 } from './DiamondCutFacet2.js';