/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiamondCutFacet } from './DiamondCutFacet.js';
export type { DiamondCutFacet3 } from './DiamondCutFacet3.js';