/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OwnershipFacet__factory } from './OwnershipFacet__factory.js';
export { OwnershipFacet3__factory } from './OwnershipFacet3__factory.js';