/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from './extensions/index.js';
export type { extensions };
export type { ERC1155 } from './ERC1155.js';
export type { IERC1155 } from './IERC1155.js';
export type { IERC1155Receiver } from './IERC1155Receiver.js';