/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC165__factory } from './IERC165__factory.js';
export { IERC1652__factory } from './IERC1652__factory.js';