/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC1155MetadataURI__factory } from './IERC1155MetadataURI__factory.js';
export { IERC1155MetadataURI3__factory } from './IERC1155MetadataURI3__factory.js';