/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  
export declare namespace LibTaskStorage {
      
    export type TaskStruct = {mainnetCollection: AddressLike, proposalId: BigNumberish, selector: BytesLike, target: AddressLike, v1: BigNumberish, v2: BigNumberish, v3: BigNumberish, currentApprovals: BigNumberish, requiredApprovals: BigNumberish, isExecuted: boolean, isActive: boolean, timestamp: BigNumberish}

    export type TaskStructOutput = [mainnetCollection: string, proposalId: bigint, selector: string, target: string, v1: bigint, v2: bigint, v3: bigint, currentApprovals: bigint, requiredApprovals: bigint, isExecuted: boolean, isActive: boolean, timestamp: bigint] & {mainnetCollection: string, proposalId: bigint, selector: string, target: string, v1: bigint, v2: bigint, v3: bigint, currentApprovals: bigint, requiredApprovals: bigint, isExecuted: boolean, isActive: boolean, timestamp: bigint }
  
    }

  export interface TaskFacet2Interface extends Interface {
    getFunction(nameOrSignature: "addCardWhitelist" | "addCardWhitelistBatch" | "getCardWhitelist" | "getCardWhitelistCount" | "getCardWhitelistPaged" | "getMyPendingTasks" | "getTask" | "getTaskCount" | "isCardWhitelisted" | "removeCardWhitelist" | "removeCardWhitelistBatch" | "syncCreateTask" | "syncUpdateStatus"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CardWhitelistAdded" | "CardWhitelistRemoved" | "StatsUpdated" | "TaskCreated" | "TaskFinalized"): EventFragment;

    encodeFunctionData(functionFragment: 'addCardWhitelist', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'addCardWhitelistBatch', values: [AddressLike, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'getCardWhitelist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCardWhitelistCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCardWhitelistPaged', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMyPendingTasks', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTask', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTaskCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'isCardWhitelisted', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'removeCardWhitelist', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'removeCardWhitelistBatch', values: [AddressLike, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'syncCreateTask', values: [AddressLike[], AddressLike, BigNumberish, BytesLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'syncUpdateStatus', values: [BigNumberish, BigNumberish, boolean, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addCardWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addCardWhitelistBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCardWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCardWhitelistCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCardWhitelistPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMyPendingTasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTaskCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCardWhitelisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeCardWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeCardWhitelistBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'syncCreateTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'syncUpdateStatus', data: BytesLike): Result;
  }

  
    export namespace CardWhitelistAddedEvent {
      export type InputTuple = [card: AddressLike, user: AddressLike];
      export type OutputTuple = [card: string, user: string];
      export interface OutputObject {card: string, user: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CardWhitelistRemovedEvent {
      export type InputTuple = [card: AddressLike, user: AddressLike];
      export type OutputTuple = [card: string, user: string];
      export interface OutputObject {card: string, user: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StatsUpdatedEvent {
      export type InputTuple = [hourIndex: BigNumberish, card: AddressLike, user: AddressLike];
      export type OutputTuple = [hourIndex: bigint, card: string, user: string];
      export interface OutputObject {hourIndex: bigint, card: string, user: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCreatedEvent {
      export type InputTuple = [taskId: BigNumberish, collection: AddressLike, pId: BigNumberish];
      export type OutputTuple = [taskId: bigint, collection: string, pId: bigint];
      export interface OutputObject {taskId: bigint, collection: string, pId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskFinalizedEvent {
      export type InputTuple = [taskId: BigNumberish];
      export type OutputTuple = [taskId: bigint];
      export interface OutputObject {taskId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TaskFacet2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): TaskFacet2;
    waitForDeployment(): Promise<this>;

    interface: TaskFacet2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCardWhitelist: TypedContractMethod<
      [card: AddressLike, user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addCardWhitelistBatch: TypedContractMethod<
      [card: AddressLike, users: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    getCardWhitelist: TypedContractMethod<
      [card: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getCardWhitelistCount: TypedContractMethod<
      [card: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getCardWhitelistPaged: TypedContractMethod<
      [card: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getMyPendingTasks: TypedContractMethod<
      [user: AddressLike, ],
      [LibTaskStorage.TaskStructOutput[]],
      'view'
    >
    

    
    getTask: TypedContractMethod<
      [taskId: BigNumberish, ],
      [LibTaskStorage.TaskStructOutput],
      'view'
    >
    

    
    getTaskCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isCardWhitelisted: TypedContractMethod<
      [card: AddressLike, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    removeCardWhitelist: TypedContractMethod<
      [card: AddressLike, user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeCardWhitelistBatch: TypedContractMethod<
      [card: AddressLike, users: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    syncCreateTask: TypedContractMethod<
      [admins: AddressLike[], collection: AddressLike, pId: BigNumberish, sel: BytesLike, target: AddressLike, v1: BigNumberish, v2: BigNumberish, v3: BigNumberish, current: BigNumberish, required: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    syncUpdateStatus: TypedContractMethod<
      [taskId: BigNumberish, newCurrent: BigNumberish, executed: boolean, signer: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCardWhitelist'): TypedContractMethod<
      [card: AddressLike, user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addCardWhitelistBatch'): TypedContractMethod<
      [card: AddressLike, users: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCardWhitelist'): TypedContractMethod<
      [card: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCardWhitelistCount'): TypedContractMethod<
      [card: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCardWhitelistPaged'): TypedContractMethod<
      [card: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getMyPendingTasks'): TypedContractMethod<
      [user: AddressLike, ],
      [LibTaskStorage.TaskStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTask'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [LibTaskStorage.TaskStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTaskCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isCardWhitelisted'): TypedContractMethod<
      [card: AddressLike, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'removeCardWhitelist'): TypedContractMethod<
      [card: AddressLike, user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeCardWhitelistBatch'): TypedContractMethod<
      [card: AddressLike, users: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'syncCreateTask'): TypedContractMethod<
      [admins: AddressLike[], collection: AddressLike, pId: BigNumberish, sel: BytesLike, target: AddressLike, v1: BigNumberish, v2: BigNumberish, v3: BigNumberish, current: BigNumberish, required: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'syncUpdateStatus'): TypedContractMethod<
      [taskId: BigNumberish, newCurrent: BigNumberish, executed: boolean, signer: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CardWhitelistAdded'): TypedContractEvent<CardWhitelistAddedEvent.InputTuple, CardWhitelistAddedEvent.OutputTuple, CardWhitelistAddedEvent.OutputObject>;
getEvent(key: 'CardWhitelistRemoved'): TypedContractEvent<CardWhitelistRemovedEvent.InputTuple, CardWhitelistRemovedEvent.OutputTuple, CardWhitelistRemovedEvent.OutputObject>;
getEvent(key: 'StatsUpdated'): TypedContractEvent<StatsUpdatedEvent.InputTuple, StatsUpdatedEvent.OutputTuple, StatsUpdatedEvent.OutputObject>;
getEvent(key: 'TaskCreated'): TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
getEvent(key: 'TaskFinalized'): TypedContractEvent<TaskFinalizedEvent.InputTuple, TaskFinalizedEvent.OutputTuple, TaskFinalizedEvent.OutputObject>;

    filters: {
      
      'CardWhitelistAdded(address,address)': TypedContractEvent<CardWhitelistAddedEvent.InputTuple, CardWhitelistAddedEvent.OutputTuple, CardWhitelistAddedEvent.OutputObject>;
      CardWhitelistAdded: TypedContractEvent<CardWhitelistAddedEvent.InputTuple, CardWhitelistAddedEvent.OutputTuple, CardWhitelistAddedEvent.OutputObject>;
    

      'CardWhitelistRemoved(address,address)': TypedContractEvent<CardWhitelistRemovedEvent.InputTuple, CardWhitelistRemovedEvent.OutputTuple, CardWhitelistRemovedEvent.OutputObject>;
      CardWhitelistRemoved: TypedContractEvent<CardWhitelistRemovedEvent.InputTuple, CardWhitelistRemovedEvent.OutputTuple, CardWhitelistRemovedEvent.OutputObject>;
    

      'StatsUpdated(uint256,address,address)': TypedContractEvent<StatsUpdatedEvent.InputTuple, StatsUpdatedEvent.OutputTuple, StatsUpdatedEvent.OutputObject>;
      StatsUpdated: TypedContractEvent<StatsUpdatedEvent.InputTuple, StatsUpdatedEvent.OutputTuple, StatsUpdatedEvent.OutputObject>;
    

      'TaskCreated(uint256,address,uint256)': TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
      TaskCreated: TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
    

      'TaskFinalized(uint256)': TypedContractEvent<TaskFinalizedEvent.InputTuple, TaskFinalizedEvent.OutputTuple, TaskFinalizedEvent.OutputObject>;
      TaskFinalized: TypedContractEvent<TaskFinalizedEvent.InputTuple, TaskFinalizedEvent.OutputTuple, TaskFinalizedEvent.OutputObject>;
    
    };
  }