/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LibDiamond__factory } from './LibDiamond__factory.js';
export { LibDiamond3__factory } from './LibDiamond3__factory.js';