/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { LibDiamond3, LibDiamond3Interface } from "../../../../CoNETIndexTaskdiamond/libraries/LibDiamond.sol/LibDiamond3.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "previousOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "OwnershipTransferred",
    "type": "event"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212201516c5dfc446b6df1b44ce728afdad069aec56d4d8396c5a0791686891bf597a64736f6c63430008210033";

  
      type LibDiamond3ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibDiamond3ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibDiamond3__factory extends ContractFactory {
    
      constructor(...args: LibDiamond3ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibDiamond3 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibDiamond3__factory {
      return super.connect(runner) as LibDiamond3__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibDiamond3Interface {
      return new Interface(_abi) as LibDiamond3Interface;
    }
    
    override attach(address: string | Addressable): LibDiamond3 {
      return super.attach(address) as LibDiamond3;
    }
  static connect(address: string, runner?: ContractRunner | null): LibDiamond3 {
      return new Contract(address, _abi, runner) as unknown as LibDiamond3;
    }
  }

  
  