/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IUserCardCtx4, IUserCardCtx4Interface } from "../../../BeamioUserCard/RedeemModule.sol/IUserCardCtx4.js";

  const _abi = [
  {
    "inputs": [],
    "name": "factoryGateway",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IUserCardCtx4__factory {
    static readonly abi = _abi;
    static createInterface(): IUserCardCtx4Interface {
      return new Interface(_abi) as IUserCardCtx4Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IUserCardCtx4 {
      return new Contract(address, _abi, runner) as unknown as IUserCardCtx4;
    }
  }
  