/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IUserCardCtx5, IUserCardCtx5Interface } from "../../../BeamioUserCard/RedeemModule.sol/IUserCardCtx5.js";

  const _abi = [
  {
    "inputs": [],
    "name": "factoryGateway",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IUserCardCtx5__factory {
    static readonly abi = _abi;
    static createInterface(): IUserCardCtx5Interface {
      return new Interface(_abi) as IUserCardCtx5Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IUserCardCtx5 {
      return new Contract(address, _abi, runner) as unknown as IUserCardCtx5;
    }
  }
  