/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155Burnable } from './ERC1155Burnable.js';
export type { ERC1155Burnable2 } from './ERC1155Burnable2.js';