/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAccessControl } from './IAccessControl.js';
export type { IAccessControl3 } from './IAccessControl3.js';