/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Permit__factory } from './IERC20Permit__factory.js';
export { IERC20Permit3__factory } from './IERC20Permit3__factory.js';