/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { Strings4, Strings4Interface } from "../../../../contracts/utils/Strings.sol/Strings4.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      }
    ],
    "name": "StringsInsufficientHexLength",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StringsInvalidAddressFormat",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StringsInvalidChar",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220bbd0eeb7fa77576556283aa90d67862c5a495149d44e8268afdc4ab2a99d713764736f6c63430008210033";

  
      type Strings4ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: Strings4ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Strings4__factory extends ContractFactory {
    
      constructor(...args: Strings4ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Strings4 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Strings4__factory {
      return super.connect(runner) as Strings4__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): Strings4Interface {
      return new Interface(_abi) as Strings4Interface;
    }
    
    override attach(address: string | Addressable): Strings4 {
      return super.attach(address) as Strings4;
    }
  static connect(address: string, runner?: ContractRunner | null): Strings4 {
      return new Contract(address, _abi, runner) as unknown as Strings4;
    }
  }

  
  