/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { BeamioUserCardPlaceholder3, BeamioUserCardPlaceholder3Interface } from "../../../BeamioUserCard/BeamioUserCardPlaceholder.sol/BeamioUserCardPlaceholder3.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "placeholder",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608080604052346026575f80546001600160a01b0319163317905561011f908161002b8239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c9081638da5cb5b1460c95750639e75143c14602f575f80fd5b3460c5575f36600319011260c557604080519081016001600160401b0381118282101760b157604052601e8152604060208201917f54686973206973206120706c616365686f6c64657220636f6e7472616374000083528151928391602083525180918160208501528484015e5f828201840152601f01601f19168101030190f35b634e487b7160e01b5f52604160045260245ffd5b5f80fd5b3460c5575f36600319011260c5575f546001600160a01b03168152602090f3fea2646970667358221220ef760641ee48f683242094800cf88534c23dceec27b9d29cd5a2b4f0d9f3783564736f6c63430008210033";

  
      type BeamioUserCardPlaceholder3ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: BeamioUserCardPlaceholder3ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class BeamioUserCardPlaceholder3__factory extends ContractFactory {
    
      constructor(...args: BeamioUserCardPlaceholder3ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<BeamioUserCardPlaceholder3 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): BeamioUserCardPlaceholder3__factory {
      return super.connect(runner) as BeamioUserCardPlaceholder3__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): BeamioUserCardPlaceholder3Interface {
      return new Interface(_abi) as BeamioUserCardPlaceholder3Interface;
    }
    
    override attach(address: string | Addressable): BeamioUserCardPlaceholder3 {
      return super.attach(address) as BeamioUserCardPlaceholder3;
    }
  static connect(address: string, runner?: ContractRunner | null): BeamioUserCardPlaceholder3 {
      return new Contract(address, _abi, runner) as unknown as BeamioUserCardPlaceholder3;
    }
  }

  
  