/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BeamioOracle__factory } from './BeamioOracle__factory.js';
export { BeamioOracle2__factory } from './BeamioOracle2__factory.js';