/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  
export declare namespace LibCatalogStorage {
      
    export type CardMetaStruct = {card: AddressLike, creator: AddressLike, name: string, description: string, uri: string, currency: BigNumberish, priceE18: BigNumberish, cardType: BigNumberish, saleStart: BigNumberish, saleEnd: BigNumberish, active: boolean, createdAt: BigNumberish, updatedAt: BigNumberish}

    export type CardMetaStructOutput = [card: string, creator: string, name: string, description: string, uri: string, currency: bigint, priceE18: bigint, cardType: bigint, saleStart: bigint, saleEnd: bigint, active: boolean, createdAt: bigint, updatedAt: bigint] & {card: string, creator: string, name: string, description: string, uri: string, currency: bigint, priceE18: bigint, cardType: bigint, saleStart: bigint, saleEnd: bigint, active: boolean, createdAt: bigint, updatedAt: bigint }
  
    }

export declare namespace CatalogFacet {
      
    export type AggregatedCatalogStatsStruct = {totalCreated: BigNumberish, totalMetaUpdated: BigNumberish, totalActivated: BigNumberish, totalDeactivated: BigNumberish}

    export type AggregatedCatalogStatsStructOutput = [totalCreated: bigint, totalMetaUpdated: bigint, totalActivated: bigint, totalDeactivated: bigint] & {totalCreated: bigint, totalMetaUpdated: bigint, totalActivated: bigint, totalDeactivated: bigint }
  

    export type RegisterCardInputStruct = {card: AddressLike, creator: AddressLike, name: string, description: string, uri: string, currency: BigNumberish, priceE18: BigNumberish, cardType: BigNumberish, saleStart: BigNumberish, saleEnd: BigNumberish, ts: BigNumberish}

    export type RegisterCardInputStructOutput = [card: string, creator: string, name: string, description: string, uri: string, currency: bigint, priceE18: bigint, cardType: bigint, saleStart: bigint, saleEnd: bigint, ts: bigint] & {card: string, creator: string, name: string, description: string, uri: string, currency: bigint, priceE18: bigint, cardType: bigint, saleStart: bigint, saleEnd: bigint, ts: bigint }
  

    export type SetActiveInputStruct = {card: AddressLike, active: boolean, ts: BigNumberish}

    export type SetActiveInputStructOutput = [card: string, active: boolean, ts: bigint] & {card: string, active: boolean, ts: bigint }
  

    export type UpdateCardMetaInputStruct = {card: AddressLike, name: string, description: string, uri: string, currency: BigNumberish, priceE18: BigNumberish, newCardType: BigNumberish, saleStart: BigNumberish, saleEnd: BigNumberish, ts: BigNumberish}

    export type UpdateCardMetaInputStructOutput = [card: string, name: string, description: string, uri: string, currency: bigint, priceE18: bigint, newCardType: bigint, saleStart: bigint, saleEnd: bigint, ts: bigint] & {card: string, name: string, description: string, uri: string, currency: bigint, priceE18: bigint, newCardType: bigint, saleStart: bigint, saleEnd: bigint, ts: bigint }
  
    }

export declare namespace LibCatalogStatsStorage {
      
    export type HourlyCatalogStatsStruct = {collectionsCreated: BigNumberish, metaUpdated: BigNumberish, activated: BigNumberish, deactivated: BigNumberish, hasData: boolean}

    export type HourlyCatalogStatsStructOutput = [collectionsCreated: bigint, metaUpdated: bigint, activated: bigint, deactivated: bigint, hasData: boolean] & {collectionsCreated: bigint, metaUpdated: bigint, activated: bigint, deactivated: bigint, hasData: boolean }
  
    }

  export interface CatalogFacet2Interface extends Interface {
    getFunction(nameOrSignature: "cardExists" | "getAllCardsCount" | "getAllCardsPaged" | "getCardMeta" | "getCatalogAggregatedStats" | "getCatalogCreatorHourly" | "getCatalogHourly" | "getCatalogStatsSince" | "getCatalogTypeHourly" | "getCreatorCardsCount" | "getCreatorCardsPaged" | "getTypeCardsCount" | "getTypeCardsPaged" | "registerCard" | "setCardActive" | "updateCardMeta"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CardActiveChanged" | "CardMetaUpdated" | "CardRegistered" | "CatalogStatsUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'cardExists', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAllCardsCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllCardsPaged', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCardMeta', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCatalogAggregatedStats', values: [BigNumberish, AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCatalogCreatorHourly', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCatalogHourly', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCatalogStatsSince', values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCatalogTypeHourly', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCreatorCardsCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCreatorCardsPaged', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTypeCardsCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTypeCardsPaged', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerCard', values: [CatalogFacet.RegisterCardInputStruct]): string;
encodeFunctionData(functionFragment: 'setCardActive', values: [CatalogFacet.SetActiveInputStruct]): string;
encodeFunctionData(functionFragment: 'updateCardMeta', values: [CatalogFacet.UpdateCardMetaInputStruct]): string;

    decodeFunctionResult(functionFragment: 'cardExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllCardsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllCardsPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCardMeta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCatalogAggregatedStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCatalogCreatorHourly', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCatalogHourly', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCatalogStatsSince', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCatalogTypeHourly', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreatorCardsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreatorCardsPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTypeCardsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTypeCardsPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerCard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCardActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCardMeta', data: BytesLike): Result;
  }

  
    export namespace CardActiveChangedEvent {
      export type InputTuple = [card: AddressLike, active: boolean];
      export type OutputTuple = [card: string, active: boolean];
      export interface OutputObject {card: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CardMetaUpdatedEvent {
      export type InputTuple = [card: AddressLike, operator: AddressLike];
      export type OutputTuple = [card: string, operator: string];
      export interface OutputObject {card: string, operator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CardRegisteredEvent {
      export type InputTuple = [card: AddressLike, creator: AddressLike, cardType: BigNumberish];
      export type OutputTuple = [card: string, creator: string, cardType: bigint];
      export interface OutputObject {card: string, creator: string, cardType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CatalogStatsUpdatedEvent {
      export type InputTuple = [hourIndex: BigNumberish, creator: AddressLike, cardType: BigNumberish];
      export type OutputTuple = [hourIndex: bigint, creator: string, cardType: bigint];
      export interface OutputObject {hourIndex: bigint, creator: string, cardType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CatalogFacet2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): CatalogFacet2;
    waitForDeployment(): Promise<this>;

    interface: CatalogFacet2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cardExists: TypedContractMethod<
      [card: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getAllCardsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAllCardsPaged: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getCardMeta: TypedContractMethod<
      [card: AddressLike, ],
      [LibCatalogStorage.CardMetaStructOutput],
      'view'
    >
    

    
    getCatalogAggregatedStats: TypedContractMethod<
      [mode: BigNumberish, account: AddressLike, cardType: BigNumberish, startTimestamp: BigNumberish, endTimestamp: BigNumberish, ],
      [CatalogFacet.AggregatedCatalogStatsStructOutput],
      'view'
    >
    

    
    getCatalogCreatorHourly: TypedContractMethod<
      [creator: AddressLike, hourIndex: BigNumberish, ],
      [LibCatalogStatsStorage.HourlyCatalogStatsStructOutput],
      'view'
    >
    

    
    getCatalogHourly: TypedContractMethod<
      [hourIndex: BigNumberish, ],
      [LibCatalogStatsStorage.HourlyCatalogStatsStructOutput],
      'view'
    >
    

    
    getCatalogStatsSince: TypedContractMethod<
      [mode: BigNumberish, account: AddressLike, cardType: BigNumberish, startTimestamp: BigNumberish, ],
      [CatalogFacet.AggregatedCatalogStatsStructOutput],
      'view'
    >
    

    
    getCatalogTypeHourly: TypedContractMethod<
      [cardType: BigNumberish, hourIndex: BigNumberish, ],
      [LibCatalogStatsStorage.HourlyCatalogStatsStructOutput],
      'view'
    >
    

    
    getCreatorCardsCount: TypedContractMethod<
      [creator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getCreatorCardsPaged: TypedContractMethod<
      [creator: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getTypeCardsCount: TypedContractMethod<
      [cardType: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getTypeCardsPaged: TypedContractMethod<
      [cardType: BigNumberish, offset: BigNumberish, limit: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    registerCard: TypedContractMethod<
      [in_: CatalogFacet.RegisterCardInputStruct, ],
      [void],
      'nonpayable'
    >
    

    
    setCardActive: TypedContractMethod<
      [in_: CatalogFacet.SetActiveInputStruct, ],
      [void],
      'nonpayable'
    >
    

    
    updateCardMeta: TypedContractMethod<
      [in_: CatalogFacet.UpdateCardMetaInputStruct, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cardExists'): TypedContractMethod<
      [card: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getAllCardsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAllCardsPaged'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCardMeta'): TypedContractMethod<
      [card: AddressLike, ],
      [LibCatalogStorage.CardMetaStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCatalogAggregatedStats'): TypedContractMethod<
      [mode: BigNumberish, account: AddressLike, cardType: BigNumberish, startTimestamp: BigNumberish, endTimestamp: BigNumberish, ],
      [CatalogFacet.AggregatedCatalogStatsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCatalogCreatorHourly'): TypedContractMethod<
      [creator: AddressLike, hourIndex: BigNumberish, ],
      [LibCatalogStatsStorage.HourlyCatalogStatsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCatalogHourly'): TypedContractMethod<
      [hourIndex: BigNumberish, ],
      [LibCatalogStatsStorage.HourlyCatalogStatsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCatalogStatsSince'): TypedContractMethod<
      [mode: BigNumberish, account: AddressLike, cardType: BigNumberish, startTimestamp: BigNumberish, ],
      [CatalogFacet.AggregatedCatalogStatsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCatalogTypeHourly'): TypedContractMethod<
      [cardType: BigNumberish, hourIndex: BigNumberish, ],
      [LibCatalogStatsStorage.HourlyCatalogStatsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCreatorCardsCount'): TypedContractMethod<
      [creator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCreatorCardsPaged'): TypedContractMethod<
      [creator: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTypeCardsCount'): TypedContractMethod<
      [cardType: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTypeCardsPaged'): TypedContractMethod<
      [cardType: BigNumberish, offset: BigNumberish, limit: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'registerCard'): TypedContractMethod<
      [in_: CatalogFacet.RegisterCardInputStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCardActive'): TypedContractMethod<
      [in_: CatalogFacet.SetActiveInputStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCardMeta'): TypedContractMethod<
      [in_: CatalogFacet.UpdateCardMetaInputStruct, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CardActiveChanged'): TypedContractEvent<CardActiveChangedEvent.InputTuple, CardActiveChangedEvent.OutputTuple, CardActiveChangedEvent.OutputObject>;
getEvent(key: 'CardMetaUpdated'): TypedContractEvent<CardMetaUpdatedEvent.InputTuple, CardMetaUpdatedEvent.OutputTuple, CardMetaUpdatedEvent.OutputObject>;
getEvent(key: 'CardRegistered'): TypedContractEvent<CardRegisteredEvent.InputTuple, CardRegisteredEvent.OutputTuple, CardRegisteredEvent.OutputObject>;
getEvent(key: 'CatalogStatsUpdated'): TypedContractEvent<CatalogStatsUpdatedEvent.InputTuple, CatalogStatsUpdatedEvent.OutputTuple, CatalogStatsUpdatedEvent.OutputObject>;

    filters: {
      
      'CardActiveChanged(address,bool)': TypedContractEvent<CardActiveChangedEvent.InputTuple, CardActiveChangedEvent.OutputTuple, CardActiveChangedEvent.OutputObject>;
      CardActiveChanged: TypedContractEvent<CardActiveChangedEvent.InputTuple, CardActiveChangedEvent.OutputTuple, CardActiveChangedEvent.OutputObject>;
    

      'CardMetaUpdated(address,address)': TypedContractEvent<CardMetaUpdatedEvent.InputTuple, CardMetaUpdatedEvent.OutputTuple, CardMetaUpdatedEvent.OutputObject>;
      CardMetaUpdated: TypedContractEvent<CardMetaUpdatedEvent.InputTuple, CardMetaUpdatedEvent.OutputTuple, CardMetaUpdatedEvent.OutputObject>;
    

      'CardRegistered(address,address,uint8)': TypedContractEvent<CardRegisteredEvent.InputTuple, CardRegisteredEvent.OutputTuple, CardRegisteredEvent.OutputObject>;
      CardRegistered: TypedContractEvent<CardRegisteredEvent.InputTuple, CardRegisteredEvent.OutputTuple, CardRegisteredEvent.OutputObject>;
    

      'CatalogStatsUpdated(uint256,address,uint8)': TypedContractEvent<CatalogStatsUpdatedEvent.InputTuple, CatalogStatsUpdatedEvent.OutputTuple, CatalogStatsUpdatedEvent.OutputObject>;
      CatalogStatsUpdated: TypedContractEvent<CatalogStatsUpdatedEvent.InputTuple, CatalogStatsUpdatedEvent.OutputTuple, CatalogStatsUpdatedEvent.OutputObject>;
    
    };
  }