/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiamondLoupeFacet } from './DiamondLoupeFacet.js';
export type { DiamondLoupeFacet3 } from './DiamondLoupeFacet3.js';