/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as beamioErc1155LogicSol from './BeamioERC1155Logic.sol/index.js';
export * as beamioUserCardSol from './BeamioUserCard.sol/index.js';